"""
github_self_modifier.py
=======================
The network modifies its OWN source code and commits to GitHub.

This is the "self-evolution" component — inspired by:
  - Developmental AI (architecture evolving like a growing organism)
  - The network's architecture IS its DNA; GitHub history = evolutionary record

WHAT IT DOES:
  1. After each growth event, regenerates dynamic_net_evolved.py with current architecture
  2. Commits to GitHub with a message describing what changed and WHY
  3. Tags significant milestones (e.g., "first_100_neurons")
  4. Logs a human-readable growth journal

SETUP REQUIRED:
  pip install gitpython
  git init your project
  Set GITHUB_TOKEN env var (or use SSH)
"""

import os
import json
import textwrap
from datetime import datetime
from typing import Dict, List
from pathlib import Path

try:
    import git
    GIT_AVAILABLE = True
except ImportError:
    GIT_AVAILABLE = False
    print("[SelfModifier] WARNING: gitpython not installed. Run: pip install gitpython")


EVOLVED_FILE_TEMPLATE = '''"""
dynamic_net_evolved.py  ← AUTO-GENERATED by the network itself
======================
This file was automatically rewritten by SelfExpandingNet.
Generation : {generation}
Timestamp  : {timestamp}
Growth events so far: {growth_events}

DO NOT EDIT MANUALLY — this file evolves with the network.
"""

import torch
import torch.nn as nn

# ============================================================
# CURRENT ARCHITECTURE  (evolved from training)
# ============================================================
# Input  : {input_size}
# Hidden : {hidden_desc}
# Output : {output_size}
# Total params: {total_params:,}
# ============================================================

CURRENT_ARCHITECTURE = {arch_json}

GROWTH_HISTORY = {growth_history}


def build_current_net():
    """Reconstruct the network with its current evolved architecture."""
    import sys
    sys.path.insert(0, str(__file__).replace("dynamic_net_evolved.py", ""))
    from dynamic_net import SelfExpandingNet

    hidden = [layer["out"] for layer in CURRENT_ARCHITECTURE["hidden_layers"]]
    net = SelfExpandingNet(
        input_size   = CURRENT_ARCHITECTURE["input_size"],
        output_size  = CURRENT_ARCHITECTURE["output_size"],
        initial_hidden = hidden
    )
    return net


if __name__ == "__main__":
    net = build_current_net()
    print(net)
    print(f"Architecture evolved over {{len(GROWTH_HISTORY)}} events")
'''


class GitHubSelfModifier:
    """
    Handles the network's ability to modify its own source code
    and push changes to GitHub automatically.
    """

    def __init__(self,
                 repo_path: str,
                 remote_name: str = "origin",
                 branch: str = "main",
                 auto_push: bool = False):   # Set True when ready to push
        """
        Args:
            repo_path  : path to your git repo root
            remote_name: usually "origin"
            branch     : "main" or "master"
            auto_push  : if True, pushes to GitHub after each commit
        """
        self.repo_path   = Path(repo_path)
        self.remote_name = remote_name
        self.branch      = branch
        self.auto_push   = auto_push
        self.generation  = 0
        self.journal     = []   # human-readable growth journal

        self.repo = None
        if GIT_AVAILABLE:
            try:
                self.repo = git.Repo(repo_path)
                print(f"[SelfModifier] Connected to git repo: {repo_path}")
                print(f"  Branch: {branch} | Auto-push: {auto_push}")
            except git.InvalidGitRepositoryError:
                print(f"[SelfModifier] Not a git repo: {repo_path}")
                print(f"  Run: git init {repo_path}")
        else:
            print("[SelfModifier] Running in dry-run mode (no git)")

    # ------------------------------------------------------------------ #
    #  MAIN CALL — call this after any growth event                       #
    # ------------------------------------------------------------------ #
    def on_growth_event(self, net, growth_event: dict, loss: float,
                        step: int):
        """
        Called automatically after network grows.
        1. Rewrites evolved source file
        2. Commits to git with descriptive message
        3. Logs to growth journal
        """
        self.generation += 1
        arch = net.get_architecture()

        # 1. Rewrite source code
        self._rewrite_evolved_file(net, arch, growth_event)

        # 2. Write growth journal entry
        self._write_journal_entry(arch, growth_event, loss, step)

        # 3. Commit to git
        self._commit(arch, growth_event, step)

        print(f"  [SelfModify] Generation {self.generation} committed to git")

    # ------------------------------------------------------------------ #
    #  REWRITE THE EVOLVED FILE                                           #
    # ------------------------------------------------------------------ #
    def _rewrite_evolved_file(self, net, arch: dict, growth_event: dict):
        hidden_desc = " → ".join(
            str(l["out"]) for l in arch["hidden_layers"]
        )
        content = EVOLVED_FILE_TEMPLATE.format(
            generation    = self.generation,
            timestamp     = datetime.now().isoformat(),
            growth_events = arch["growth_events"],
            input_size    = arch["input_size"],
            hidden_desc   = hidden_desc,
            output_size   = arch["output_size"],
            total_params  = arch["total_params"],
            arch_json     = json.dumps(arch, indent=4),
            growth_history= json.dumps(net.growth_log[-20:], indent=4)  # last 20
        )

        out_path = self.repo_path / "dynamic_net_evolved.py"
        with open(out_path, "w") as f:
            f.write(content)

    # ------------------------------------------------------------------ #
    #  WRITE JOURNAL ENTRY                                                #
    # ------------------------------------------------------------------ #
    def _write_journal_entry(self, arch: dict, event: dict,
                             loss: float, step: int):
        entry = {
            "generation":    self.generation,
            "timestamp":     datetime.now().isoformat(),
            "step":          step,
            "loss":          round(loss, 6),
            "event":         event,
            "architecture":  arch,
            "meaning":       self._explain_event(event, arch)
        }
        self.journal.append(entry)

        # Write journal file
        journal_path = self.repo_path / "growth_journal.json"
        with open(journal_path, "w") as f:
            json.dump(self.journal, f, indent=2)

    # ------------------------------------------------------------------ #
    #  EXPLAIN the growth event in human language (for commit message)    #
    # ------------------------------------------------------------------ #
    def _explain_event(self, event: dict, arch: dict) -> str:
        etype = event.get("type", "unknown")

        if etype == "width_growth":
            return (f"Layer {event['layer']} was struggling (high NES gradient score). "
                    f"Added {event['added']} neurons. "
                    f"Network now has {arch['total_params']:,} parameters.")

        elif etype == "depth_growth":
            ratio = event.get('entropy_ratio', 0)
            return (f"Network was {ratio*100:.0f}% uncertain about its predictions. "
                    f"Added a new hidden layer to improve understanding.")

        elif etype == "plateau":
            return (f"Loss stopped improving. "
                    f"Added capacity to push through the plateau.")
        else:
            return "Architecture evolved."

    # ------------------------------------------------------------------ #
    #  GIT COMMIT                                                         #
    # ------------------------------------------------------------------ #
    def _commit(self, arch: dict, event: dict, step: int):
        if not GIT_AVAILABLE or self.repo is None:
            print(f"  [DryRun] Would commit: Gen {self.generation} — {event.get('type')}")
            return

        try:
            # Stage changed files
            self.repo.index.add([
                "dynamic_net_evolved.py",
                "growth_journal.json"
            ])

            # Build commit message
            hidden_sizes = [str(l["out"]) for l in arch["hidden_layers"]]
            msg = (
                f"[SENN Gen {self.generation}] {event.get('type', 'growth')} at step {step}\n\n"
                f"Architecture: {arch['input_size']} → {' → '.join(hidden_sizes)} → {arch['output_size']}\n"
                f"Total params: {arch['total_params']:,}\n"
                f"Trigger: {event.get('trigger', 'auto')}\n"
                f"Reason: {self._explain_event(event, arch)}\n\n"
                f"This commit was generated autonomously by the neural network."
            )

            self.repo.index.commit(msg)

            # Tag milestones
            total = arch["total_params"]
            for milestone in [100, 500, 1000, 5000, 10000]:
                prev_total = total - event.get("added", 0) * 10   # rough estimate
                if prev_total < milestone <= total:
                    tag_name = f"milestone_{milestone}_params"
                    self.repo.create_tag(tag_name, message=f"Reached {milestone} parameters!")
                    print(f"  [Git] Tagged milestone: {tag_name}")

            # Optionally push to GitHub
            if self.auto_push:
                origin = self.repo.remote(name=self.remote_name)
                origin.push(self.branch)
                print(f"  [Git] Pushed to {self.remote_name}/{self.branch}")

        except Exception as e:
            print(f"  [Git] Commit failed: {e}")

    # ------------------------------------------------------------------ #
    #  SETUP HELPER — print instructions for first-time setup            #
    # ------------------------------------------------------------------ #
    @staticmethod
    def print_setup_instructions(repo_path: str, github_url: str):
        print(textwrap.dedent(f"""
        ╔══════════════════════════════════════════════════════╗
        ║         GITHUB SELF-MODIFIER SETUP GUIDE            ║
        ╠══════════════════════════════════════════════════════╣
        ║  Run these commands ONCE to set up your repo:       ║
        ║                                                      ║
        ║  cd {repo_path:<44} ║
        ║  git init                                            ║
        ║  git remote add origin {github_url:<29} ║
        ║  git add .                                           ║
        ║  git commit -m "initial: baby SENN born"             ║
        ║  git push -u origin main                             ║
        ║                                                      ║
        ║  Then set auto_push=True in GitHubSelfModifier()    ║
        ╚══════════════════════════════════════════════════════╝
        """))
